import streamlit as st import numpy as np import pandas as pd import yfinance as yf from scipy.optimize import brentq

st.set_page_config(page_title="Institutional Derivatives Lab", layout="wide") st.markdown("<style>.stMetric { background-color: #ffffff; padding: 20px; border-radius: 12px; border: 1px solid #e2e8f0; }</style>", unsafe_allow_html=True)

with st.sidebar: st.header("🏢 Product Architect") mode = st.selectbox("Structure", ["FCN Version 1", "FCN Version 2 (Step-Down)", "BCN Solver"]) tks_in = st.text_input("Underlying Basket", "AMZN, ALB") tks = [x.strip().upper() for x in tks_in.split(",")] st.divider() stk_pct = st.slider("Put Strike (%)", 40, 100, 75) ko_pct = st.slider("Autocall Level (%)", 80, 120, 100) freq_opt = st.selectbox("Coupon Frequency", ["Monthly", "Quarterly"]) freq_m = 1 if freq_opt == "Monthly" else 3 tenor = st.number_input("Tenor (Years)", 0.25, 5.0, 1.0, 0.25) nc_m = st.number_input("Non-Call (Months)", 0, 24, 3) st.divider() rf_source = st.selectbox("Base Rate Source", ["3m T-Bill", "1 Year UST", "SOFR", "3m T-Bill + Spread"]) spread = st.slider("Spread (%)", 0.0, 5.0, 1.0, 0.1) if "Spread" in rf_source else 0.0

@st.cache_data(ttl=600) def get_mkt(tickers): v, p, d, names = [], [], [], [] for t in tickers: s = yf.Ticker(t); h = s.history(period="2y")['Close'] if h.empty: continue p.append(h); names.append(t) d.append(s.info.get('dividendYield', 0.012) or 0.012) v.append(h.pct_change().tail(252).std() * np.sqrt(252)) return np.array(v), pd.concat(p, axis=1).pct_change().dropna().corr().values, np.array(d), names

def run_mc(cpn, paths, r, t, stk, ko, f_m, nc_m, mode, sd): steps, n_s, _ = paths.shape wo = np.min(paths, axis=2) obs = np.arange(int((f_m/12)*252), steps, int((f_m/12)*252)) pay, act, acc = np.zeros(n_s), np.ones(n_s, dtype=bool), np.zeros(n_s) c_val = (cpn * (f_m/12)) * 100 for i, step in enumerate(obs): cur_ko = ko - (i * sd) if "Version 2" in mode else ko acc[act] += c_val if step >= int((nc_m/12)*252): k = act & (wo[step] >= cur_ko) pay[k] = 100 + acc[k]; act[k] = False if np.any(act): pay[act] = np.where(wo[-1, act] >= stk, 100, wo[-1, act]) + acc[act] return np.mean(pay) * np.exp(-r * t), (np.sum(wo[-1] < stk)/n_s)

st.title(f"🚀 {mode} Terminal") if st.button("RUN PRICING"): vols, corr, divs, names = get_mkt(tks) n_s, n_d = 15000, int(tenor * 252) L = np.linalg.cholesky(corr + np.eye(len(vols)) * 1e-10) dt = 1/252 drift = (r_final - divs - 0.5 * vols**2) * dt noise = np.einsum('ij,tkj->tki', L, np.random.standard_normal((n_d, n_s, len(vols)))) rets = drift + (vols * np.sqrt(dt)) * noise paths = np.vstack([np.ones((1, n_s, len(vols)))*100, 100 * np.exp(np.cumsum(rets, axis=0))])
